# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followertoorg',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Member'),
        ),
        migrations.AlterField(
            model_name='officertoorg',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Member'),
        ),
        migrations.AlterField(
            model_name='phototouser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Member'),
        ),
        migrations.AlterField(
            model_name='posttouser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Member'),
        ),
        migrations.AlterField(
            model_name='usertoorg',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Member'),
        ),
        migrations.AlterField(
            model_name='usertopost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Member'),
        ),
    ]
