# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-26 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170625_0422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officertoorg',
            old_name='user',
            new_name='officer',
        ),
        migrations.AddField(
            model_name='phototoevent',
            name='photo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Photo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phototoorg',
            name='photo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Photo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phototopost',
            name='photo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Photo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phototouser',
            name='photo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Photo'),
            preserve_default=False,
        ),
    ]
